### PR TITLE
arg parsing, minor name changes and fixes

### PR DESCRIPTION
**Pull request by jpocwiar**
- renamed main.py to rendering.py
- enclosed ray tracing in function so that it could be run from other file
- added new main.py where parsing takes place
- added config.ini for default params
- added utils.py for utils function

### CODE REVIEW

**Comment by kuhyx** [comment]
1. Why requirements.txt was removed?
2. It would be nice to have option to define the scene as an argument  (see in rendering.py
`    scene = [add_sphere([.75, .1, 1.], .6, [1., 0., 0.]),
             add_sphere([-.75, .1, 2.25], .6, [0., 1., 0.]),
             add_sphere([-2.75, .1, 3.5], .6, [0., 0., 1.]),
             add_plane([0., -.5, 0.], [0., 1., 0.]),
             ]
`
Please try to parametrize them

**Comment by jpocwiar** [comment]
1. Was a mistake, it is back now
2. Do we need to do that? I admit it could be a cool functionality for the current program state, but at the end we are supposed to load .obj file as our scene, so we will not define it in code, hence enhancing that functionality seems needless.
3. I added .obj and .hdr arguments for ray tracing (not used now) and dedicated folders for the files

**Comment by kuhyx** [comment]
👍 for 1 and 3
For 2. If it will take you longer than 10 minutes to implement then do not bother, I just do not believe that we will be able to import scene from blender directly atm, and this will be simply easier

**Comment by jpocwiar** [comment]
Ok, I did varying number of spheres, which is something. Parametrizing everything would be too much mess in parameters IMO.

**Pull request merged**
